quarkus:
  application:
    name: Gestion de Docentes
    version: 1.0-SNAPSHOT

  # HTTP
  http:
    port: 8860
    host: localhost
    root-path: kick
    cors: true
    cors-origins: '*'
    cors-methods: GET,POST,PUT,DELETE,OPTIONS
    cors-headers: Content-Type,Authorization,X-Requested-With


  # Base de datos
  datasource:
    db-kind: h2
    username: admin
    password: 12345
    jdbc:
      #url: "jdbc:h2:mem:gdocente"
      file: ./data/gdocentes_db

  # Hibernate-hibernate-orm:
  hibernate-orm:
    schema-management:
      strategy:
        drop-and-create
    log:
      sql: true


  # Configuracion de Logs
  log:
    level: INFO
    console:
      enabled: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      dark-launch: true

    file:
      enabled: true
      path: logs/gestudiantes.log
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      rotation:
        max-file-size: 5M # Tamaño máximo
        max-backup-index: 5 # Archivos conservados
        file-suffix: yyyy-MM-dd #Sufijo de retación

  swagger-ui:
    enabled: true
    always-include: true
    path: "/swager-ui"
    title: "Gestion de docentes demo - Vinni"
    description: "API generado en Quarkus para gestion de Docentes"
    version: "V1"
    contact-name: "vinni9@gmail.com"

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: "Gestion de docentes"
          version: "1.1.0"
